server:
  servlet:
    encoding:
      # 한글깨짐 처리 
      force-response: true

# Spring Data Source 설정 
spring:

  output:
    ansi:
      enabled: always 

  # mustache (1. 루트폴더 변경, 2. 타임리프 캐시 설정 변경)
  mustache:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .mustache
    cache: false

