AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Lambda Sample Template \n"
Parameters:
  DefaultName:
    Type: String
    Default: test-lambda
  ServiceType:
    Type: String
    Default: Tutorial
  PythonVersion:
    Type: String
    Default: python3.13
  StageType:
    Type: String
    Default: latest
Globals:
  Function:
    Runtime:
      Fn::Sub: ${PythonVersion}
    MemorySize: 3072
    Timeout: 900
    Layers:
    - Ref: SharedLayer
    Tags:
      ServiceType:
        Fn::Sub: ${ServiceType}
      DefaultName:
        Fn::Sub: ${DefaultName}
    AutoPublishAlias:
      Ref: StageType
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
      - Fn::Sub: ${PythonVersion}
      ContentUri: s3://lambda-good593/build/course-aws/lambda/fdcd53b52e0121c590f748f97bd3a3c5
      Description: Provides the base backend shared library and dependencies
      LayerName:
        Fn::Sub: ${ServiceType}-${DefaultName}-shared-layer
    Metadata:
      BuildMethod: python3.13
      SamResourceId: SharedLayer
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ServiceType}-${DefaultName}
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      CodeUri: s3://lambda-good593/build/course-aws/lambda/773f91009ef7e5c9cad5b6140d6c5ac0
      Handler: app.lambda_handler
      Tags:
        Name:
          Fn::Sub: ${ServiceType}-${DefaultName}
        Service:
          Fn::Sub: ${ServiceType}
    Metadata:
      SamResourceId: TestLambda
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ServiceType}-${DefaultName}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
    Metadata:
      SamResourceId: LambdaRole
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: ${ServiceType}-${DefaultName}-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:AbortMultipartUpload
          - s3:ListBucket
          - s3:DeleteObject
          - s3:GetObjectVersion
          - s3:ListMultipartUploadParts
          Resource: '*'
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
      Roles:
      - Ref: LambdaRole
    Metadata:
      SamResourceId: LambdaPolicy
