AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Lambda Sample Template
##########################################################################
#   Parameters
#   https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
##########################################################################
Parameters:
  DefaultName:
    Type: String
    Default: test-lambda
  ServiceType:
    Type: String
    Default: Tutorial
  PythonVersion:
    Type: String
    Default: python3.13
  StageType:
    Type: String
    Default: latest

##########################################################################
#   Globals
#   https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
##########################################################################
Globals:
  Function:
    Runtime: !Sub ${PythonVersion}
    MemorySize: 3072
    Timeout: 900
    Layers:
      # - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:layer이름:버전(숫자)
      - !Ref SharedLayer
    Tags:
      ServiceType: !Sub ${ServiceType}
      DefaultName: !Sub ${DefaultName}
    AutoPublishAlias: !Ref StageType

Resources:
  ##########################################################################
  #   AWS::Serverless::LayerVersion
  #   https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-resource-layerversion.html
  #   AWS Lambda에서 사용할 공통 라이브러리 
  ##########################################################################
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - !Sub ${PythonVersion}
      ContentUri: layer
      Description: Provides the base backend shared library and dependencies
      LayerName: !Sub ${ServiceType}-${DefaultName}-shared-layer
    Metadata:
      BuildMethod: !Sub ${PythonVersion} # Required to have AWS SAM build this layer
  ########################################################################## 
  #   AWS::Serverless::Function
  #   https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-resource-function.html
  #   AWS 테스트 람다 
  ##########################################################################
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ServiceType}-${DefaultName}
      Role: !GetAtt LambdaRole.Arn
      CodeUri: src
      Handler: app.lambda_handler
      Tags:
        Name: !Sub ${ServiceType}-${DefaultName}
        Service: !Sub ${ServiceType}
      Layers:
        - !Ref SharedLayer
  ##########################################################################
  #   AWS::IAM::Role
  #   https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  #   AWS Lambda 권한 
  ##########################################################################
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceType}-${DefaultName}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
  ##########################################################################
  #   AWS::IAM::Policy
  #   https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
  #   AWS Lambda 정책
  ##########################################################################
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ServiceType}-${DefaultName}-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:AbortMultipartUpload
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetObjectVersion
              - s3:ListMultipartUploadParts
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Roles:
        - !Ref LambdaRole